# Sample Prometheus Configuration for DCGM Exporter
# Add this scrape configuration to your existing prometheus.yml

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'dcgm-superpod'

scrape_configs:
  # DCGM Exporter - GPU metrics with HPC job labels
  - job_name: 'dcgm_exporter'
    # Option 1: File-based service discovery (recommended with BCM role monitor)
    file_sd_configs:
      - files:
          - '/cm/shared/apps/dcgm-exporter/prometheus-targets/*.json'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [job]
        regex: 'dcgm_exporter'
        action: keep
    metric_relabel_configs:
      - target_label: cluster
        replacement: slurm
      # Drop internal Go metrics to reduce cardinality
      - source_labels: [__name__]
        regex: '^go_.*'
        action: drop

  # Alternative: Static configuration (if not using BCM role monitor)
  # - job_name: 'dcgm_exporter_static'
  #   static_configs:
  #     - targets:
  #         - 'dgx-01:9400'
  #         - 'dgx-02:9400'
  #         - 'dgx-03:9400'
  #       labels:
  #         cluster: 'slurm'
  #   metric_relabel_configs:
  #     - target_label: cluster
  #       replacement: slurm

  # Optional: If you also deployed Jobstats exporters
  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
          - '/cm/shared/apps/dcgm-exporter/prometheus-targets/*.json'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [job]
        regex: 'node_exporter'
        action: keep
    metric_relabel_configs:
      - target_label: cluster
        replacement: slurm
      - source_labels: [__name__]
        regex: '^go_.*'
        action: drop

  - job_name: 'cgroup_exporter'
    file_sd_configs:
      - files:
          - '/cm/shared/apps/dcgm-exporter/prometheus-targets/*.json'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [job]
        regex: 'cgroup_exporter'
        action: keep
    metric_relabel_configs:
      - target_label: cluster
        replacement: slurm

  - job_name: 'nvidia_gpu_exporter'
    file_sd_configs:
      - files:
          - '/cm/shared/apps/dcgm-exporter/prometheus-targets/*.json'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [job]
        regex: 'gpu_exporter'
        action: keep
    metric_relabel_configs:
      - target_label: cluster
        replacement: slurm

# Storage configuration example for GPU metrics
# GPU metrics can generate significant data volume
# storage:
#   tsdb:
#     path: /var/lib/prometheus/data
#     retention.time: 30d
#     retention.size: 100GB

